# Generated by Django 3.1.11 on 2021-11-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('router', '0003_gatewayendpoint_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ip', models.CharField(max_length=40)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.outgoingresponse')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.gatewayroute')),
            ],
        ),
    ]
