# Generated by Django 3.1.11 on 2021-11-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingrequest',
            name='response',
        ),
        migrations.AddField(
            model_name='incomingrequest',
            name='resp_status',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='OutgoingResponse',
        ),
    ]
