# Generated by Django 3.1.11 on 2021-11-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmanager', '0002_auto_20211116_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingrequest',
            name='resp_size',
            field=models.IntegerField(default=0),
        ),
    ]
