# Generated by Django 3.1.11 on 2021-11-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayEndpoint',
            fields=[
                ('endpoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint_description', models.CharField(max_length=200)),
                ('endpoint_path', models.CharField(max_length=100, unique=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetURL',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_description', models.CharField(max_length=200)),
                ('url_path', models.CharField(max_length=300, unique=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayRoute',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.gatewayendpoint')),
                ('targeturl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.targeturl')),
            ],
        ),
    ]
