# Generated by Django 3.1.11 on 2021-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_auto_20211116_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayendpoint',
            name='stream',
            field=models.BooleanField(default=False),
        ),
    ]
